### PR TITLE
chore(deps): bump minimum peer dependency bound with `semantic-release`

### LINKED ISSUE #902: Bump minimum bound for peer dependencies with `semantic-release`
> Just a quick fyi to keep in mind: to use the newly added logger in core, we'll need to bump the minimum bound of the peer dependency, which is a breaking change

_Originally posted by @travi in https://github.com/semantic-release/github/pull/874#discussion_r1720828079_

### LINKED ISSUE #920: successCommentCondition not able to check PR labels
I am trying to limit the success comments to only PRs which have not been released on a specific channel already. I am doing this by setting the successCommentCondition to check if a PR has the respective "released on @\<channel>" label already or not. If it does then success commenting should be skipped.

In a nutshell, I am trying to avoid this on PRs:

image

I tried doing it [the way specified in the README.md file](https://github.com/semantic-release/github/blob/master/README.md?plain=1#L205) but after testing it I realized that it might be incorrect. This is because within the [Pull Request GitHub API response](https://docs.github.com/en/rest/pulls/pulls?apiVersion=2022-11-28#get-a-pull-request), the "labels" key is an array of objects which is why the loadash method `-.includes` would not work there.

So instead I tried to set the successCommentCondition this way using the loadash method `-.some` after locally testing with a sample API response:
```
    [
      "@semantic-release/github",
      {
        successCommentCondition:
          "<% return !issue.labels?.some((label) => { return label.name === ('released on @beta'); }) %>"
      }
    ],
```
The snippet above still did not work. My PRs with the label `released on @beta` are still getting commented on if I back-merge the main branch tags to the beta branch.

Can I please get some guidance on this, is it my syntax or is this potentially a bug with the plugin?

Thanks!

### PR DESCRIPTION
**Pull request by babblebey**
This PR Bumps the minimum bound of the `semantic-release` peer dependency in order to allow the plugin to consume the new `warn` function added in https://github.com/semantic-release/semantic-release/pull/3423 

BREAKING CHANGE: the minimum required version of `semantic-release` to use `@semantic-release/github` is now [v24.1.0](https://github.com/semantic-release/semantic-release/releases/tag/v24.1.0)

### Related Issue

Resolves #902 
Fixes #920

### CODE REVIEW

**Comment by travi** [comment]
i would recommend including the change that is prompting this breaking change in this PR. that way the reasoning for the breaking change is more clear in the release. i would keep the breaking change as a separate commit from the other changes. that way we can merge without squashing and the release notes generated by semantic-release will list the breaking change for the peer dependency bump as well as the change(s) for the use of the new feature from core.

**Comment by babblebey** [comment]
> i would recommend including the change that is prompting this breaking change in this PR. that way the reasoning for the breaking change is more clear in the release.

Yea, this I did with b7577aa and 85d0ad0 but the PR was failing CI with the error below in some unit tests....

```
TypeError {
  message: 'logger.warn is not a function',
}
```
...hence I thought to revert. 

> that way we can merge without squashing and the release notes generated by semantic-release will list the breaking change for the peer dependency bump as well as the change(s) for the use of the new feature from core.

This looks good YES, but does that will mean we do a "Merge Commit"?? If so, maybe it will be better to just redo this PR in-order to avoid the "Revert" commits showing up in release notes and on master branch commit history (this is assuming we're good to allow the PR fly regardless of the failing unit test in CI) 🤔 

What'd you think?

**Comment by travi** [comment]
> the good news about this is that the tests were failing for a good reason. they were highlighting that changing the peer dependency was not enough for the new usage of the new logger function to work properly. keep in mind that a peer-dependency definition is only declaring the range that is considered to be compatible with the intended usage. to satisfy the peer-dependency requirement, we also need to actually depend on a compatible version. we take care of that requirement by capturing a dev-dependency on semantic-release for usage in the tests.

i looked at this a little more closely and realized the the devDependency was already updated, likely by renovate. it confused me since that change wasnt part of this PR. so, that leaves me unsure about why specifically your tests failed, but it still comes down to the error you shared:

> TypeError {
>   message: 'logger.warn is not a function',
> }

that is still highlighting that the logger function you are attempting to use is not available in that context for some reason. we need that to work to give us more confidence that it will work after releasing the change in a real context. it is worth investigating to understand what is causing that failure and resolving it as part of this change

**Comment by babblebey** [comment]
> yes. personally, i tend to prefer normal merges most of the time because it allows us to tell more of the story than a single commit does. semantic-release does a great job of communicating the details when it has more commits to work with.

I totally agree with how semantic-release handles commit, the more commits the richer the details in the release note; better than just a single line change in the release note.

> but git also has great flexibility to modify the history of a branch, so we could choose to take the steps to clean up the story in the existing branch that is tied to this PR. i think there is value in learning those capabilities of git at some point in anyone's learning journey, and i'm happy to help if youre interested as part of this.

I am very interested in this for sure 😃 

> we need that to work to give us more confidence that it will work after releasing the change in a real context. it is worth investigating to understand what is causing that failure and resolving it as part of this change

Yea, I'll do some digs

**Comment by babblebey** [comment]
> Yea, I'll do some digs

...and It didn't take any longer than 40secs to figure that I was missing the mock `warn` method in the test `context.logger`, I mean I figured the `logger` function within the test context isn't even real in the first place.... soo. 😆 

> so we could choose to take the steps to clean up the story in the existing branch that is tied to this PR..

And I figured this out too 😉, guess I just needed to know it was possible, thanks for that 😁

**Comment by travi** [comment]
> And I figured this out too 😉, guess I just needed to know it was possible, thanks for that 😁

awesome! great work! 

might need to do it one more time, though. since we'll be doing a normal merge rather than a squash, we need to make sure that we include the `BREAKING CHANGE: ` footer in the breaking commit(s) so that we end up communicating the breaking nature of the release with a major version bump. i think this is the commit that will need that: [`b7577aa` (#916)](https://github.com/semantic-release/github/pull/916/commits/b7577aa78bf804c666049190ae4a6e803290554f)

> I was missing the mock `warn` method in the test `context.logger`

ah, that makes sense. quick fix for that situation, then. unfortunately, that doesnt add a lot of confidence that the combination of the core update and the usage in this plugin integrate successfully, just because the integration is mocked. do you happen to be aware whether that is exercised by the integration test? this is pretty low risk, and i see no reason to expect it not to work, but knowing that it is executed somewhere without resulting in an error would help some with confidence.

**Comment by travi** [comment]
one other thing to consider before we merge this... since we attempt to avoid unnecessary breaking changes too often, knowing that we will be releasing a major version here makes it a good opportunity to consider whether there are any other breaking changes that we should group with this. nothing is coming to my mind, but worth considering in case anything more comes to mind (that wouldnt require significant investment)

**Comment by babblebey** [comment]
> we need to make sure that we include the `BREAKING CHANGE: ` footer in the breaking commit(s) so that we end up communicating the breaking nature of the release with a major version bump

Yea, will do... gotta be the case since we're merging commits 😉 

> just because the integration is mocked. do you happen to be aware whether that is exercised by the integration test? this is pretty low risk, and i see no reason to expect it not to work, but knowing that it is executed somewhere without resulting in an error would help some with confidence.

Yea, it is captured in the integrations test for sure, BUT I'll give this is real-life test for that confidence YES

> edit: defining a support policy for GHES could be something worth considering

Yes, I remember that when you said it https://github.com/semantic-release/github/issues/910#issuecomment-2325514927, But how do we go about that

**Comment by babblebey** [comment]
So, I found a possible `BREAKING CHANGE` candidate for this PR, it's a fix for this https://github.com/semantic-release/github/issues/920

Here's what we're doing https://github.com/semantic-release/github/issues/920#issuecomment-2347143966

**Comment by travi** [comment]
> But how do we go about it???

my thought is that this is basically just a documentation change and using the breaking release to make folks aware of the stance. since this would be specific to the github plugin, i think that documentation likely makes the most sense in the readme of this plugin. the fact that we bundle the github plugin into the core package by default potentially complicates some of that, though

we talked about adding checks against the api schema as part of our verification suite, which i think is valuable to follow through on, but i think that can be separate from defining the support range and documenting it.

however, i'm not sure we are well enough prepared to make such a stance as part of this release. the somewhat difficult decision that i think we need to consider is whether that is a rolling range based on GitHub's EOL schedule for GHES versions, or a static one where we would plan to make a breaking release each time we drop support for specific old versions. the latter option feels tedious without providing a lot of value, but the former option better communicates when an actual version falls out of our support in a way that better honors the intention of breaking.

**Comment by babblebey** [comment]
> the fact that we bundle the github plugin into the core package by default potentially complicates some of that, though

Yea, following this BREAKING CHANGE, we still have to do a feature release to trigger this plugin update on core I believe 

we talked about adding checks against the api schema as part of our verification suite, which i think is valuable to follow through on, but i think that can be separate from defining the support range and documenting it.

So, what do you say??? We go get this one merged... and Look towards planning the GHES Support policy, with a check in the verify lifecycle for it, and documenting supported range.

**Comment by babblebey** [comment]
> and i see no reason to expect it not to work, but knowing that it is executed somewhere without resulting in an error would help some with confidence.

image

I thought to quickly let you know with the screenshot above... the `logger.warn` works

**Comment by travi** [comment]
> So, what do you say??? We go get this one merged... and Look towards planning the GHES Support policy, with a check in the verify lifecycle for it, and documenting supported range.

i'm ok with this not making this major release. i think the other changes are only breaking for the github plugin, correct? i think it could be argued that the GHES support range definition would be as breaking for the core package since github is included by default, so in a way, including that with this release would make it _more_ breaking than this release currently is

**Review by travi — APPROVED** [review]

**Review by gr2m — APPROVED** [review]
🚀

**Pull request merged**
