### PR TITLE
Feat/draft and prerelease

### PR DESCRIPTION
**Pull request by sebbrandt87**
see 
- https://developer.github.com/v3/repos/releases/#create-a-release
- https://octokit.github.io/rest.js/#api-Repos-createRelease
- https://help.github.com/articles/creating-releases/

### CODE REVIEW

**Comment by pvdlg** [comment]
The support of `prerelease` is support in [v16.0.0-beta.1](https://github.com/semantic-release/semantic-release/releases/tag/v16.0.0-beta.1%40beta). It's done based on the branch configuration and what commit is merged where, so it's dynamic.

Doing it in a static way as you did in the PR doesn't bring much value (the value of prerelease will always be what you "hardcode" in your semantic-release config and won't be dynamic).

I would suggest to open an issue to ask us about a feature in the future, as [mentioned in our contribution guidelines](https://github.com/semantic-release/semantic-release/blob/v16.0.0-beta.1%40beta/CONTRIBUTING.md#submitting-a-pull-request), to avoid spending time on a feature that is already implemented or in progress.

**Comment by sebbrandt87** [comment]
I saw nothing regarding the usage of the draft and prerelease feature and we need it and will use it within business workflows to fullfill from a draft after a review to deployments were a human factor is important but should be automated away as much as possible.

But if the implementation is usable for us, cool. Otherwise I did the patch anyway for now.

**Comment by pvdlg** [comment]
If you want to make releases for test purpose or to distribute them to a limited group of users, and then making them available to everyone once validated by a human we recommend using [distribution channels](https://github.com/semantic-release/semantic-release/blob/beta/docs/recipes/distribution-channels.md) or [pre releases](https://github.com/semantic-release/semantic-release/blob/beta/docs/recipes/pre-releases.md).

The problem of validating releases only within GitHub is that you might also release somewhere else (npm or other) and those release would already be out before human validation.

So we think the solutions I link above, using the beta version `16.0.0`, are a more global solution than just creating every release with the `prerelease` flag and validating by unchecking it.

If it's the workflow want to go with you can creating your own plugin as a fork of this one.

**Comment by sebbrandt87** [comment]
I have the feeling that you pin this specific to the `prerelease` flag.
I am more interested in the `draft` flag and could live without the `prerelease` being configurable but instead detectable as you already said it will be.
So would a PR with only `draft` be okay or not?

**Comment by pvdlg** [comment]
It's kind of the same problem with `draft`. semantic-release can make releases in multiple places and there is no concept of draft release there. For most package managers all releases are final, you can't delete them or un-publish them. So it's the same principle with semantic-release, we don't have the concept of draft releases by design, because when a release is published some users might start depending on them so we don't want to pull them back. This is why you can't unpublish from npm for example.

The definition of the GitHub `draft` property is:
> `true` to create a draft (unpublished) release, `false` to create a published one. Default: `false`

However, as mentioned above, all semantic-release releases are published.

It would be quite misleading to set `draft` to `true`, as you could have a release being published on npm (where there is no concept of draft) but being a draft (unpublished) in Github. Moreover, if you decide this release should not become final and keep it as a draft, then it will stay in some inconsistent state, where it's final and released on npm, but not on GitHub.

We think using pre-releases is a better way to handle the situation of releases that have to be published to be tested but shouldn't be considered finals.
You could have a `rc` branch that release pre-releases, and the human approval step, would be to merge `rc` into `master` rather than unchecking `draft`.
That has several advantages:
- You can continue to release fixes on `master` while a release is pending approval
- If a release is not approved you don't have an inconsistent state and you can just continue to push code on `rc` and make releases until it's approved

**Comment by sebbrandt87** [comment]
Okay I did not thought about changing in the github plugin the release outcome I would need to think about outher publish endpoints as this is why it is already in different plugins. I would think about the a logic check with a combination like github draft: true -> npm not allowed to be published for example.
Anyway I see your point.

**Comment by pvdlg** [comment]
> I would think about a logic check with a combination like github draft: true -> npm not allowed to be published for example

That would not be possible without a huge design change in semantic-release. Currently semantic-release is controlled by git only (e.g. pushes and merges of commits). What you are suggesting is that semantic-release would also receive inputs from other sources like the draft field in the GitHub release. That's a huge departure from what semantic-release is. And I'm not even talking about the complexity of a workflow with multiple steps executed asynchronously (i.e. how to make the workflow "wait" until someone uncheck the `draft` to release on npm?)

Anyway, we are not going to go that direction. Git will stay the only way to trigger semantic-release and as far as I can tell it doesn't prevent to implement a workflow with a human validation. The validation as to be done via Git by merging from a branch to another. Just open a PR from `rc` to `master`, click on merge when you think the release is good.
You can develop a tool that automate the opening of the PR or that would trigger that merge on a button click.

**Pull request closed without merging**
