### PR TITLE
fix: address `@octokit/rest` deprecations

### LINKED ISSUE #248: An in-range update of @octokit/rest is breaking the build 🚨
## The dependency [@octokit/rest](https://github.com/octokit/rest.js) was updated from `16.41.2` to `16.42.0`.

🚨 [View failing branch](https://github.com/semantic-release/github/compare/master...semantic-release:greenkeeper%2F%40octokit%2Frest-16.42.0).

This version is **covered** by your **current version range** and after updating it in your project **the build failed**.

@octokit/rest is a direct dependency of this project, and **it is very likely causing it to break**. If other packages depend on yours, this update is probably also breaking those in turn.

<details>
<summary>Status Details</summary>

- ❌ **continuous-integration/travis-ci/push:** The Travis CI build failed ([Details](https://travis-ci.org/semantic-release/github/builds/645239497?utm_source=github_status&utm_medium=notification)).
</details>

---

<details>
<summary>Release Notes for v16.42.0</summary>

<h1><a href="https://urls.greenkeeper.io/octokit/rest.js/compare/v16.41.2...v16.42.0">16.42.0</a> (2020-02-03)</h1>
<h3>Features</h3>
<ul>
<li>deprecate <code>const Octokit = require("@octokit/rest")</code> in favor of <code>const { Octokit } = require("@octokit/rest")</code> (<a href="https://urls.greenkeeper.io/octokit/rest.js/commit/bbc3e48205d2cd1c3d2ccbca680482d5aaf9976d">bbc3e48</a>)</li>
</ul>
</details>

<details>
<summary>Commits</summary>
<p>The new version differs by 2 commits.</p>
<ul>
<li><a href="https://urls.greenkeeper.io/octokit/rest.js/commit/bbc3e48205d2cd1c3d2ccbca680482d5aaf9976d"><code>bbc3e48</code></a> <code>feat: deprecate <code>const Octokit = require("@octokit/rest")</code> in favor of <code>const { Octokit } = require("@octokit/rest")</code></code></li>
<li><a href="https://urls.greenkeeper.io/octokit/rest.js/commit/d1ad1612e49e2dfa650ae3d4e9ccc9f9b7d38490"><code>d1ad161</code></a> <code>test: deprecate <code>const Octokit = require("@octokit/rest")</code> in favor of <code>const { Octokit } = require("@octokit/rest")</code></code></li>
</ul>
<p>See the <a href="https://urls.greenkeeper.io/octokit/rest.js/compare/cb78528db09cac3257aa7a0f3e45c5f25c1a1177...bbc3e48205d2cd1c3d2ccbca680482d5aaf9976d">full diff</a></p>
</details>

<details>
<summary>FAQ and help</summary>

There is a collection of [frequently asked questions](https://greenkeeper.io/faq.html). If those don’t help, you can always [ask the humans behind Greenkeeper](https://github.com/greenkeeperio/greenkeeper/issues/new).
</details>

---

Your [Greenkeeper](https://greenkeeper.io) Bot :palm_tree:

### PR DESCRIPTION
**Pull request by gr2m**
closes #248

### CODE REVIEW

**Comment by gr2m** [comment]
I'm confused I don't understand why the tests are failing, I'll have to digg some more into it

**Comment by gr2m** [comment]
Something very funky is going on. I'll continue looking into it tomorrow.

It seems that the tests pass again without my other changes: https://github.com/semantic-release/github/issues/248#issuecomment-581207432 so there is no urgency

**Comment by gr2m** [comment]
All right, this one is ready

**Comment by pvdlg** [comment]
Can you squash your commits before merging (as in don't split changes between `fix` and `test` if the tests changes are related to the fix)?

The goal is to have atomic commits, so in the future when we look at the git history we know what goes with what. That also prevent mistakes in case we have to rollback a change. With atomic commits we can rollback any one commit without have to worry about forgetting to also rollback another one.

**Comment by gr2m** [comment]
I usually split them out so I have a test commit that has failing CI and then a fix/feature commit that is green, to make sure that the test is actually doing what it is supposed to do. In this case I had to `push --force` to clean up commits

If you like we can enforce squash merging for the semantic-release repos. 

Other than that, is this good to merge?

**Comment by pvdlg** [comment]
During the PR phase we can do pretty whatever we want.  what's important is for the commits that end up on `master` to be atomic.

We could enforce squash merging , but there might some rare cases were we open one PR and do two things. For example I happened to have PR that both increase the minimum node version and update something else. In that case I keep 2 commits, 1 for the Node upgrade, 1 for the other thing.

Regarding the code changes, yes we can merge. Not sure if #250 is necessary though, we can upgrade to v17 once it's out of beta.

**Comment by gr2m** [comment]
> We could enforce squash merging , but there might some rare cases were we open one PR and do two things. For example I happened to have PR that both increase the minimum node version and update something else

In these cases I often times edit the release notes after the release

> Not sure if #250 is necessary though, we can upgrade to v17 once it's out of beta.

It was just me testing, I'm not planning on merging it until v17 stable is released

**Pull request merged**
