### PR TITLE
feat: add 'draftRelease' option

### LINKED ISSUE #275: creating a draft release
is it possible to create a **draft only** release? 

that is, run the whole process, but keep the release labelled as "draft" in github (otherwise referred to as "pre-release" in GitHub's UI and not to be confused with `semantic-release`'s `prerelease` flag on branches)

I looked through issues and examples in this repo and there was no such example, the only reference to "draft" was in-line and doesn't seem to be specifically flaggable ...

to further distinguish from workflow with `prerelease` flag, I intend to continue using a single main branch and not looking to implement the workflows as [described](https://semantic-release.gitbook.io/semantic-release/usage/workflow-configuration#release-branches) rather, just make the final github release flagged as "draft" upon publishing.

### PR DESCRIPTION
**Pull request by BetaHuhn**
### Summary

This PR adds a new `draftRelease` option which, when set to true, will create a GitHub draft release instead of publishing an actual GitHub Release. The option defaults to false and will thus not impact current users.

Fixes #275

### CODE REVIEW

**Comment by BetaHuhn** [comment]
Any plans to merge this?

Friendly ping, @gr2m

**Comment by gr2m** [comment]
Yes, as soon as we find the time to review it, I cannot tell when that will be right now, sorry

**Comment by BetaHuhn** [comment]
No problem!

**Review by baruchiro — APPROVED** [review]
I'm waiting for this, can you please prioritize?

**Comment by alex-dixon** [comment]
Maybe until there's time to review it it could be published on a draft release channel? 😄 

Some of us could give feedback, add fixes if needed, etc.

**Comment by jimCresswell** [comment]
This would be useful for us too. Happy to help if that's possible.

**Comment by tubbo** [comment]
This would also be useful to us. We'd like to use `semantic-release` as a means of releasing our Electron application, and because we need to wait for multiple parallel workflows to complete before we can mark it as released, we currently have a bit of a rube goldberg machine set up to handle use cases like multiple release channels. It would be a lot better if we could use `semantic-release` instead of combining multiple other tools together to get basically the same result.

I'd also be happy to help test and review code if that's needed. This is pretty much exactly like the implementation I have locally.

**Comment by MrSquaare** [comment]
I am also interested in this option. I have a case where I have several assets that need to be built on different operating systems. I can't have them available at release time and associate them with `@semantic-releas/github`. A draft option would allow me to proceed in several steps.

**Comment by gr2m** [comment]
Thank you all for your patience, for sharing your use cases and for your offers to help. I know it has been a long time coming. I finally got around to review it and it all looks good. I'll merge and release it shortly

**Review by gr2m — APPROVED** [review]

**Pull request merged**
