### PR TITLE
feat(verify): add option to skip permissions check

### PR DESCRIPTION
**Pull request by mo-harris**
We use GitHub App installation tokens in our CI/CD pipeline (But we don't use GitHub Actions).
This option would make it possible to use the plugin for this use case.

### CODE REVIEW

**Comment by gr2m** [comment]
According to [this response by a GitHubber](https://github.community/t5/GitHub-Actions/Retrieve-permissions-as-a-GitHub-App-Installation/td-p/25035) there is a way to retrieve the permissions an installation has on a repository. However the `"permissions"` key is not shown in the response in the documentation https://developer.github.com/v3/apps/installations/#list-repositories. so you'd need to check that first. It might likely be a mistake in the documentation, because e.g. https://developer.github.com/v3/apps/installations/#response-1 shows a "permissions" key.

If it works, we change this code

https://github.com/semantic-release/github/blob/8027e9120afb2110be40d9e224bea627f0b6361c/lib/verify.js#L57-L81

Instead of throwing the error in line 80, we could send a request to the above endpoint with

```js
const {
  repositories: [
    permissions: { contents: contentsPermission }
  ]
} = await octokit.apps.listRepos({ per_page: 1 })
if (contentsPermission !== 'write') {
 // we are good
 return
}
throw error
```

Could you give that a try please?

**Comment by mo-harris** [comment]
I checked the API, It does return `permissions` but the returned value is not correct.
```
"permissions": {
   "admin": false,
   "push": false,
   "pull": false
}
```
I'm positive the installation token has `push`, `pull`, and some other accesses but `GET installation/repositories` returns incomplete and wrong data. Considering this is also not documented, It can be a bug.

**Comment by gr2m** [comment]
Hmm I think the `"permissions":` key you see is meant for OAuth scopes, not app installation access token. It explains why everything is `false` but really it should not be there in the first place. Let me investigate

**Comment by mo-harris** [comment]
Let me know if you wanted any help

**Comment by gr2m** [comment]
I was able to reproduce the problem. I've shared a code snippet here: https://github.community/t5/GitHub-Actions/Retrieve-permissions-as-a-GitHub-App-Installation/m-p/56123#M9757. I also contacted GitHub support because I think you found a legitimate bug with the REST API.

I'll keep you posted

**Comment by mo-harris** [comment]
Thank you. Can we have this pull request merged meanwhile as a temporary solution until GitHub fixes the bug?

**Comment by gr2m** [comment]
I'd rather not, because removing that feature would be a breaking change. I would suggest you publish your own copy of this package to npm and use it as a plugin replacement for `@semantic-release/github`.

**Comment by mo-harris** [comment]
I'd rather not to clone the plugin but fair enough!
I'm going to close this pull request as the solution is not acceptable to you.
Will follow up on the GitHub community topic.

**Pull request closed without merging**
