### PR TITLE
update dependencies

### LINKED ISSUE #183: Failures during "success" step of this plugin
Hello,

I recently was doing updates and one of them was semantic-release. In doing the update I assume something else got updated along the way as I started getting this error when my releases are run:

```
An error occurred while running semantic-release: { HttpError: Empty value for parameter 'number': undefined
    at values.forEach (/home/circleci/repo/node_modules/@octokit/rest/plugins/validate/validate.js:64:15)
    at Array.forEach (<anonymous>)
    at Object.keys.forEach.parameterName (/home/circleci/repo/node_modules/@octokit/rest/plugins/validate/validate.js:38:12)
    at Array.forEach (<anonymous>)
    at validate (/home/circleci/repo/node_modules/@octokit/rest/plugins/validate/validate.js:16:23)
  name: 'HttpError',
  status: 400,
  headers: undefined,
  request: undefined,
  pluginName: '@semantic-release/github' }
{ AggregateError: 
    HttpError: Empty value for parameter 'number': undefined
        at values.forEach (/home/circleci/repo/node_modules/@octokit/rest/plugins/validate/validate.js:64:15)
        at Array.forEach (<anonymous>)
        at Object.keys.forEach.parameterName (/home/circleci/repo/node_modules/@octokit/rest/plugins/validate/validate.js:38:12)
        at Array.forEach (<anonymous>)
        at validate (/home/circleci/repo/node_modules/@octokit/rest/plugins/validate/validate.js:16:23)
    at /home/circleci/repo/node_modules/semantic-release/lib/plugins/pipeline.js:54:11 name: 'AggregateError' }error Command failed with exit code 1.
```

I downgraded semantic-release, @semantic-release/git and @semantic-release/github but I still get these failures. I suspect something else got updated that is used by @semantic-release/github that is causing this error but I am not sure what at this point. Any thoughts on what might be going on?

### PR DESCRIPTION
**Pull request by gr2m**
closes #183

### CODE REVIEW

**Comment by pvdlg** [comment]
Is this PR necessary? All the version updated are in range of their definition...

**Comment by gr2m** [comment]
It won’t hurt and it will surely resolve #183

**Comment by pvdlg** [comment]
I don't mind, but we have a lot of this issue being opened by people who do realize that they have a lockfile that lock their dependencies to outdated version.
If we have to make a PR and a release for each of those case, this is endless...

I which npm would actually explain to users the consequences of using lockfiles rather than transparently create one without explanation...

**Comment by gr2m** [comment]
Yeah I hear you. I also meant to just merge this PR without you needing to review it, I just forgot about it while waiting for CI. Sorry 😞

**Pull request merged**
