### PR TITLE
feat: add repositoryUrl to pluginConfig to override the value in context.options

### PR DESCRIPTION
**Pull request by arthurchaloin**
## What does this PR do?

It adds a (facultative) `repositoryUrl` field into the `pluginConfig`. Actions will use this value if its set, otherwise the behavior of the plugin remains unchanged.

## In what kind of use cases is this helpful?

In our use case, we have a semantic release configured to release on both GitHub and GitLab. As the repositories have different names, we couldn't find a way to pass different `repositoryUrl`s to GitHub and GitLab.

### CODE REVIEW

**Comment by pvdlg** [comment]
How come you are releasing on two different Git repo for the same project?
How is it even possible to configure your CI to clone the same project from 2 repo?

Please clarify your setup and what you are trying to achieve...

**Comment by pvdlg** [comment]
Closing as no response provided. Still don't understand how a project can exists on a GitHub and a GitLAb repo at the same time...

**Comment by arthurchaloin** [comment]
We are hosting the repo on a private GitLab, which is then mirrored to a public GitHub. However, even if the tags are mirrored, the releases are not. This is why our CI creates a release on GitLab (for internal purposes) and a public release on GitHub, all during the same pipeline.

Here is my `.releaserc.yml` : 

```yaml
plugins:
  - '@semantic-release/commit-analyzer'
  - '@semantic-release/release-notes-generator'
  - - '@semantic-release/github'
    - repositoryUrl: https://github.com/user/repo.git
      assets:
        - ./*.bin
        - ./docker-compose.yml
  - - '@semantic-release/gitlab'
    - gitlabUrl: https://gitlab.example.com
      assets:
        - ./*.bin
        - ./docker-compose.yml
```

This runs during a GitLab pipeline and just works fine.

If I don't use the `repositoryUrl` option, semantic-release will generate a remote url based on the git remote url. However in our use case, there is no way for semantic release to deduce the GitHub repository URL, so it needs to be set manually.

**Comment by pvdlg** [comment]
Thanks for clarifying. It's a bit too much of an edge case for use to implement such feature in one of our core plugin.
The problem is that such feature would rely too much on things out of our control, mainly the fact that the tags and commits have to be replicated between the repo in time for the second release to works.
I would recommend you to use your own plugin to do that, for example by forking this one.

**Comment by arthurchaloin** [comment]
Indeed, we ended up using a fork of this repo. Thanks.

**Pull request closed without merging**
