### PR TITLE
fix: missing `"PullRequest".canBeRebased` field on GHES graphql api

### LINKED ISSUE #910: CI failing with error - Field 'canBeRebased' doesn't exist on type 'PullRequest'
Hello Team, 
we use the latest version of semantic-release in our Jenkins pipeline. 
After the recent update https://github.com/semantic-release/github/pull/874 in this repo, our build is failing with the below error

```
3:18:06 PM] [semantic-release] › ✔  Completed step "publish" of plugin "@semantic-release/github"
[2024-09-02T19:18:07.347Z] [3:18:06 PM] [semantic-release] › ℹ  Start step "publish" of plugin "@semantic-release/exec"
[2024-09-02T19:18:07.347Z] [3:18:06 PM] [semantic-release] › ✔  Completed step "publish" of plugin "@semantic-release/exec"
[2024-09-02T19:18:07.347Z] [3:18:06 PM] [semantic-release] › ℹ  Start step "success" of plugin "@semantic-release/github"
[2024-09-02T19:18:08.812Z] [3:18:08 PM] [semantic-release] › ✘  Failed step "success" of plugin "@semantic-release/github"
[2024-09-02T19:18:08.812Z] [3:18:08 PM] [semantic-release] › ℹ  Start step "success" of plugin "@semantic-release/exec"
[2024-09-02T19:18:08.812Z] [3:18:08 PM] [semantic-release] › ✔  Completed step "success" of plugin "@semantic-release/exec"
[2024-09-02T19:18:08.812Z] [3:18:08 PM] [semantic-release] › ✘  An error occurred while running semantic-release: Error: Field 'canBeRebased' doesn't exist on type 'PullRequest'
[2024-09-02T19:18:08.813Z]     at file:///usr/local/lib/node_modules/semantic-release/node_modules/aggregate-error/index.js:23:26
[2024-09-02T19:18:08.813Z]     at Array.map (<anonymous>)
[2024-09-02T19:18:08.813Z]     at new AggregateError (file:///usr/local/lib/node_modules/semantic-release/node_modules/aggregate-error/index.js:16:19)
[2024-09-02T19:18:08.813Z]     at file:///usr/local/lib/node_modules/semantic-release/lib/plugins/pipeline.js:55:13
[2024-09-02T19:18:08.813Z]     at async pluginsConfigAccumulator.<computed> [as success] (file:///usr/local/lib/node_modules/semantic-release/lib/plugins/index.js:87:11)
[2024-09-02T19:18:08.813Z]     at async run (file:///usr/local/lib/node_modules/semantic-release/index.js:218:3)
[2024-09-02T19:18:08.813Z]     at async Module.default (file:///usr/local/lib/node_modules/semantic-release/index.js:278:22)
[2024-09-02T19:18:08.814Z]     at async default (file:///usr/local/lib/node_modules/semantic-release/cli.js:55:5) {
[2024-09-02T19:18:08.814Z]   path: [
[2024-09-02T19:18:08.814Z]     'query getAssociatedPRs',
[2024-09-02T19:18:08.814Z]     'repository',
[2024-09-02T19:18:08.814Z]     'commit7c472f',
[2024-09-02T19:18:08.814Z]     '... on Commit',
[2024-09-02T19:18:08.814Z]     'associatedPullRequests',
[2024-09-02T19:18:08.814Z]     'nodes',
[2024-09-02T19:18:08.814Z]     'canBeRebased'
[2024-09-02T19:18:08.814Z]   ],
[2024-09-02T19:18:08.814Z]   extensions: {
[2024-09-02T19:18:08.814Z]     code: 'undefinedField',
[2024-09-02T19:18:08.814Z]     typeName: 'PullRequest',
[2024-09-02T19:18:08.814Z]     fieldName: 'canBeRebased'
[2024-09-02T19:18:08.814Z]   },
[2024-09-02T19:18:08.814Z]   locations: [ { line: 61, column: 19 } ],
[2024-09-02T19:18:08.814Z]   pluginName: '@semantic-release/github'
[2024-09-02T19:18:08.814Z] }
[2024-09-02T19:18:08.814Z] AggregateError: 
[2024-09-02T19:18:08.814Z]     Error: Field 'canBeRebased' doesn't exist on type 'PullRequest'
[2024-09-02T19:18:08.814Z]         at Array.map (<anonymous>)
[2024-09-02T19:18:08.814Z]         at file:///usr/local/lib/node_modules/semantic-release/lib/plugins/pipeline.js:55:13
[2024-09-02T19:18:08.815Z]         at async pluginsConfigAccumulator.<computed> [as success] (file:///usr/local/lib/node_modules/semantic-release/lib/plugins/index.js:87:11)
[2024-09-02T19:18:08.815Z]         at async run (file:///usr/local/lib/node_modules/semantic-release/index.js:218:3)
[2024-09-02T19:18:08.815Z]         at async Module.default (file:///usr/local/lib/node_modules/semantic-release/index.js:278:22)
[2024-09-02T19:18:08.815Z]         at async default (file:///usr/local/lib/node_modules/semantic-release/cli.js:55:5)
[2024-09-02T19:18:08.815Z]     at file:///usr/local/lib/node_modules/[4msemantic-release[24m/lib/plugins/pipeline.js:55:13
[2024-09-02T19:18:08.815Z]     at async pluginsConfigAccumulator.<computed> [as success] (file:///usr/local/lib/node_modules/[4msemantic-release[24m/lib/plugins/index.js:87:11)
[2024-09-02T19:18:08.816Z]     at async run (file:///usr/local/lib/node_modules/[4msemantic-release[24m/index.js:218:3)
[2024-09-02T19:18:08.816Z]     at async Module.default (file:///usr/local/lib/node_modules/[4msemantic-release[24m/index.js:278:22)
[2024-09-02T19:18:08.816Z]     at async default (file:///usr/local/lib/node_modules/[4msemantic-release[24m/cli.js:55:5) {
[2024-09-02T19:18:08.816Z]   errors: [
[2024-09-02T19:18:08.816Z]     Error: Field 'canBeRebased' doesn't exist on type 'PullRequest'
[2024-09-02T19:18:08.816Z]         at file:///usr/local/lib/node_modules/[4msemantic-release[24m/node_modules/[4maggregate-error[24m/index.js:23:26
[2024-09-02T19:18:08.816Z]         at Array.map (<anonymous>)
[2024-09-02T19:18:08.816Z]         at new AggregateError (file:///usr/local/lib/node_modules/[4msemantic-release[24m/node_modules/[4maggregate-error[24m/index.js:16:19)
[2024-09-02T19:18:08.816Z]         at file:///usr/local/lib/node_modules/[4msemantic-release[24m/lib/plugins/pipeline.js:55:13
[2024-09-02T19:18:08.817Z]         at async pluginsConfigAccumulator.<computed> [as success] (file:///usr/local/lib/node_modules/[4msemantic-release[24m/lib/plugins/index.js:87:11)
[2024-09-02T19:18:08.817Z]         at async run (file:///usr/local/lib/node_modules/[4msemantic-release[24m/index.js:218:3)
[2024-09-02T19:18:08.817Z]         at async Module.default (file:///usr/local/lib/node_modules/[4msemantic-release[24m/index.js:278:22)
[2024-09-02T19:18:08.817Z]         at async default (file:///usr/local/lib/node_modules/[4msemantic-release[24m/cli.js:55:5) {
[2024-09-02T19:18:08.817Z]       path: [36m[Array][39m,
[2024-09-02T19:18:08.817Z]       extensions: [36m[Object][39m,
[2024-09-02T19:18:08.817Z]       locations: [36m[Array][39m,
[2024-09-02T19:18:08.817Z]       pluginName: [32m'@semantic-release/github'[39m
[2024-09-02T19:18:08.818Z]     }
[2024-09-02T19:18:08.818Z]   ]
[2024-09-02T19:18:08.870Z] }
Failed to complete release!
```

We are on GitHub Enterprise Server **`3.9.19`**

Please assist if any changes needs to be made to fix this. Thank you!

### PR DESCRIPTION
**Pull request by babblebey**
<a href='https://hearts.dev/projects/3/users/babblebey'></a>

This Pull Request **temporarily** removes the `canBeRebased` field from the `associatedPRs` GraphQL query requested fields due to conflict with older GitHub Enterprise graphql api version. 

**Changes Made:**

- Removed every instance of `canBeRebased` field consumption in the `success` script
- Appropriated field removal in test coverage

### Related Issues

Resolves #910

### CODE REVIEW

**Comment by jedwards1211** [comment]
Have any of y'all tested things against a deployment of GitHub Enterprise Server before, even if not in CI, just manually?

I'm tempted to ask them if we can have a license for testing purposes and mess around with manually testing against it.  I'd even be willing to figure out how to spin up temporary instance in AWS for CI testing and keep it in the free tier (I have experience using the AWS SDK) though I imagine y'all don't really want our CI tests to go that far.

**Comment by travi** [comment]
i've been in environments where GHES is the variation of GitHub available to the teams, but i have never spun up an instance specifically to test against. my understanding is that GHES is non-trivial to deploy, but i wont say i'm completely opposed to the idea if we could automate it to the point of being simple and low maintenance. 

we go fairly far with the integration tests of the core repo to spin up a temporary npm registry, an api to simulate the github api, and a temporarily hosted git repo. i think we could take that further, too, if we gave it some more attention. that would be separate from this suggestion, but just highlighting it to suggest that something like you suggest isnt totally out of the question.

i do wonder if we could accomplish enough feedback from comparing our queries against the graphql schema for the various supported versions of the github api (at least the current version and the oldest supported version that shipped with GHES). i think that would give us quite a bit of protection for the changes that are happening recently without needing to stand up a full instance of GHES and figure out a suite of tests that would exercise the calls against that deployed api. the graphql schema wouldnt protect our calls against the REST api, but we could probably expand to do similar there if we decide this is successful.

to be open, this is a challenge i face with maintaining https://github.com/repository-settings/app/ as well, so i'm very interested in progress we could make that could protect both projects

**Review by travi — APPROVED** [review]

**Comment by jedwards1211** [comment]
That's true we could check against the graphql schemas, as long as there's somewhere we can download old versions of the schema from

**Comment by jedwards1211** [comment]
@gr2m I submitted a request ~10 days to GHES sales for a license to use for testing against, but I haven't heard back from them.  Is that something you'd be able to pull some strings for?  If we can get a license I'd be happy to work on trying to put together an integration test setup with it.

**Pull request merged**
