### PR TITLE
fix: decouple successComment and releasedLabels when successComment is false

### LINKED ISSUE #421: Allow disabling successComment but adding releasedLabels
<a href='https://hearts.dev/projects/3/users/aslafy-z'></a>

Currently, when setting `successComment` to `false`, no labels are added to the released PRs. 

These two behavior could be decoupled in order to allow one (adding comments), the other (adding labels) or the two (adding comments and labels).

### PR DESCRIPTION
**Pull request by june21x**
close #421
reopened from PR #532

### CODE REVIEW

**Comment by june21x** [comment]
Hi @gr2m , I have reopened the PR.
Any help on review and merge is appreciated, thanks.

**Comment by zigang93** [comment]
Hi @gr2m , can you have a look on this PR?

**Review by aslafy-z — APPROVED** [review]
/lgtm

I'd like the tests to be run, not sure what's prevent it. Can you have a look @travi? Thanks!

**Comment by aslafy-z** [comment]
@travi any updates please?

**Pull request closed without merging**
